  Running command git clone --quiet https://github.com/huggingface/transformers.git /tmp/pip-install-4w1e8k17/transformers_0ab02edecb08430abe7cda263192cb0b
  Running command git clone --quiet https://github.com/huggingface/peft.git /tmp/pip-install-4w1e8k17/peft_19555f6822994a6987fdae4d48836658
  Running command git clone --quiet https://github.com/huggingface/accelerate.git /tmp/pip-install-4w1e8k17/accelerate_48ae199d40e7417e8f4ed2c0ccadb19a
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so.11.0'), PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
Loading checkpoint shards:   0%|          | 0/9 [00:00<?, ?it/s]Loading checkpoint shards:  11%|█         | 1/9 [00:06<00:51,  6.40s/it]Loading checkpoint shards:  22%|██▏       | 2/9 [00:13<00:46,  6.68s/it]Loading checkpoint shards:  33%|███▎      | 3/9 [00:18<00:36,  6.06s/it]Loading checkpoint shards:  44%|████▍     | 4/9 [00:24<00:30,  6.06s/it]Loading checkpoint shards:  56%|█████▌    | 5/9 [00:30<00:23,  5.87s/it]Loading checkpoint shards:  67%|██████▋   | 6/9 [00:35<00:17,  5.68s/it]Loading checkpoint shards:  78%|███████▊  | 7/9 [00:40<00:11,  5.59s/it]Loading checkpoint shards:  89%|████████▉ | 8/9 [00:46<00:05,  5.55s/it]Loading checkpoint shards: 100%|██████████| 9/9 [00:50<00:00,  5.22s/it]Loading checkpoint shards: 100%|██████████| 9/9 [00:50<00:00,  5.65s/it]
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/transformers/generation/utils.py:1261: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
